In [ ]:
import os

In [3]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [12]:
img = cv2.imread('digits.png',0)

In [13]:
print(img)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [5]:
# Split the image to 5000 cells, each of 20*20 size

In [14]:
cells = [np.hsplit(row,100) for row in np.vsplit(img,20)]

In [16]:
#cells

In [17]:
x = np.array(cells)

In [18]:
train = x[:, :50].reshape(-1, 400).astype(np.float32)

In [19]:
test = x[:,50:100].reshape(-1, 400).astype(np.float32)

In [20]:
# Create labels for train and test data
k = np.arange(10)
train_labels = np.repeat(k,250)[:, np.newaxis]

In [21]:
test_labels = train_labels.copy()

In [22]:
knn = cv2.ml.KNearest_create()

In [23]:
knn

< cv2.ml.KNearest 0x7f7daf9484d0>

In [24]:
knn.train(train, cv2.ml.ROW_SAMPLE, train_labels)

True

In [27]:
ret, result, neighbours, dist = knn.findNearest(test, k=5)

In [28]:
# Check the accurary of clarification
matches = result == test_labels

In [29]:
correct = np.count_nonzero(matches)

In [31]:
accuracy = correct*100/result.size

In [33]:
print("Accuracy is: ", accuracy, "%")

Accuracy is:  85.28 %
